In [2]:
import pandas as pd

## Using Auto Scraper :

In [3]:
from autoscraper import AutoScraper

In [5]:
cars = "https://www.cars24.com/buy-used-car/?sort=P&storeCityId=2423&pinId=411045"

In [6]:
scraper = AutoScraper()
result = scraper.build(cars,'html.parser')

### For autoscraper it is showing no results that's why we are trying with web scraper extension on chrome, so that we can extract data directly from the website on chrome. Then we can export it to csv

1. Importing dataset:

In [9]:
cars = pd.read_csv('cars24 (5).csv')
cars

,web-scraper-order,web-scraper-start-url,Link,Link-href,Name,Transmission,KM_Driven,Fuel_Type,Owner,Registration,EMI,Sales,Year,Types,Types-href,Location,Location-href
0,1668347995-478,https://www.cars24.com/buy-used-car?sort=P&sto...,"2017 Hyundai Elite i20ASTA 1.2 (O) Manual89,78...",https://www.cars24.com/buy-used-hyundai-elite-...,2017 Hyundai Elite i20 ASTA 1.2 (O),MANUAL,"89,784 km",Petrol + CNG,1st Owner,HR-26,"₹12,655/month","Fixed Price₹6,47,299",Feb 2017,CNG,https://www.cars24.com/buy-used-cng-cars-new-d...,NaN,NaN
1,1668348003-479,https://www.cars24.com/buy-used-car?sort=P&sto...,"₹25,000off2021 Maruti AltoLXI CNG Manual30,144...",https://www.cars24.com/buy-used-maruti-alto-20...,2021 Maruti Alto LXI CNG,MANUAL,"30,144 km",Petrol + CNG,1st Owner,HR-26,"₹9,396/month","₹5,05,599₹4,80,599",Feb 2021,CNG,https://www.cars24.com/buy-used-cng-cars-new-d...,NaN,NaN
2,1668348011-480,https://www.cars24.com/buy-used-car?sort=P&sto...,"2018 Maruti Alto K10LXI CNG (O) Manual83,128 k...",https://www.cars24.com/buy-used-maruti-alto-k1...,2018 Maruti Alto K10 LXI CNG (O),MANUAL,"83,128 km",Petrol + CNG,1st Owner,DL-2C,"₹7,071/month","Fixed Price₹3,61,699",Jun 2018,CNG,https://www.cars24.com/buy-used-cng-cars-new-d...,NaN,NaN
3,1668348019-481,https://www.cars24.com/buy-used-car?sort=P&sto...,"₹5,000off2016 Maruti Alto K10LXI CNG Manual55,...",https://www.cars24.com/buy-used-maruti-alto-k1...,2016 Maruti Alto K10 LXI CNG,MANUAL,"55,888 km",Petrol + CNG,2nd Owner,DL-8C,"₹6,006/month","₹3,12,199₹3,07,199",May 2016,CNG,https://www.cars24.com/buy-used-cng-cars-new-d...,NaN,NaN
4,1668348027-482,https://www.cars24.com/buy-used-car?sort=P&sto...,"₹37,700off2021 Maruti AltoLXI CNG Manual17,920...",https://www.cars24.com/buy-used-maruti-alto-20...,2021 Maruti Alto LXI CNG,MANUAL,"17,920 km",Petrol + CNG,1st Owner,DL-3C,"₹9,189/month","₹5,07,699₹4,69,999",Jul 2021,CNG,https://www.cars24.com/buy-used-cng-cars-new-d...,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
237,1668350268-715,https://www.cars24.com/buy-used-car?sort=P&sto...,"₹20,400off2018 Hyundai Grand i10SPORTZ 1.2 KAP...",https://www.cars24.com/buy-used-hyundai-grand-...,2018 Hyundai Grand i10 SPORTZ 1.2 KAPPA VTVT,MANUAL,"6,875 km",Petrol,2nd Owner,UP-16,"₹10,295/month","₹5,46,999₹5,26,599",Apr 2018,NaN,NaN,NaN,NaN
238,1668350278-716,https://www.cars24.com/buy-used-car?sort=P&sto...,"₹5,000off2010 Hyundai i10MAGNA 1.2 Manual19,94...",https://www.cars24.com/buy-used-hyundai-i10-20...,2010 Hyundai i10 MAGNA 1.2,MANUAL,"19,940 km",Petrol,1st Owner,DL-10,"₹3,353/month","₹1,76,499₹1,71,499",Sep 2010,NaN,NaN,NaN,NaN
239,1668350288-717,https://www.cars24.com/buy-used-car?sort=P&sto...,"2011 Maruti Wagon R 1.0VXI Manual28,876 km1st ...",https://www.cars24.com/buy-used-maruti-wagon-r...,2011 Maruti Wagon R 1.0 VXI,MANUAL,"28,876 km",Petrol,1st Owner,DL-9C,"₹5,523/month","Fixed Price₹2,82,499",Jun 2011,NaN,NaN,NaN,NaN
240,1668350297-718,https://www.cars24.com/buy-used-car?sort=P&sto...,SAVE₹898/m2020 KIA SELTOSHTK PLUS 1.5 PETROL M...,https://www.cars24.com/buy-used-kia-seltos-202...,2020 KIA SELTOS HTK PLUS 1.5 PETROL,MANUAL,"6,436 km",Petrol,1st Owner,DL-11,"₹21,868/month","₹11,78,199₹11,64,499",Oct 2020,NaN,NaN,NaN,NaN
241,1668350304-719,https://www.cars24.com/buy-used-car?sort=P&sto...,"₹37,600off2019 Maruti SwiftLXI Manual28,054 km...",https://www.cars24.com/buy-used-maruti-swift-2...,2019 Maruti Swift LXI,MANUAL,"28,054 km",Petrol,1st Owner,DL-9C,"₹9,693/month","₹5,33,399₹4,95,799",Nov 2019,NaN,NaN,NaN,NaN

In [8]:
cars = cars.drop(['web-scraper-order','web-scraper-start-url','Link','Link-href','Types-href'], axis=1)
cars

,Name,Transmission,KM_Driven,Fuel_Type,Owner,Registration,EMI,Sales,Year,Types
0,2017 Hyundai Elite i20 ASTA 1.2 (O),MANUAL,"89,784 km",Petrol + CNG,1st Owner,HR-26,"₹12,655/month","Fixed Price₹6,47,299",Feb 2017,CNG
1,2021 Maruti Alto LXI CNG,MANUAL,"30,144 km",Petrol + CNG,1st Owner,HR-26,"₹9,396/month","₹5,05,599₹4,80,599",Feb 2021,CNG
2,2018 Maruti Alto K10 LXI CNG (O),MANUAL,"83,128 km",Petrol + CNG,1st Owner,DL-2C,"₹7,071/month","Fixed Price₹3,61,699",Jun 2018,CNG
3,2016 Maruti Alto K10 LXI CNG,MANUAL,"55,888 km",Petrol + CNG,2nd Owner,DL-8C,"₹6,139/month","Fixed Price₹3,13,999",May 2016,CNG
4,2021 Maruti Alto LXI CNG,MANUAL,"17,920 km",Petrol + CNG,1st Owner,DL-3C,"₹9,189/month","₹5,07,699₹4,69,999",Jul 2021,CNG
...,...,...,...,...,...,...,...,...,...,...
234,2018 Hyundai Grand i10 SPORTZ 1.2 KAPPA VTVT,MANUAL,"6,875 km",Petrol,2nd Owner,UP-16,"₹10,295/month","₹5,46,999₹5,26,599",Apr 2018,NaN
235,2010 Hyundai i10 MAGNA 1.2,MANUAL,"19,940 km",Petrol,1st Owner,DL-10,"₹3,353/month","₹1,76,499₹1,71,499",Sep 2010,NaN
236,2011 Maruti Wagon R 1.0 VXI,MANUAL,"28,876 km",Petrol,1st Owner,DL-9C,"₹5,523/month","Fixed Price₹2,82,499",Jun 2011,NaN
237,2020 KIA SELTOS HTK PLUS 1.5 PETROL,MANUAL,"6,436 km",Petrol,1st Owner,DL-11,"₹21,868/month","₹11,78,199₹11,64,499",Oct 2020,NaN
238,2019 Maruti Swift LXI,MANUAL,"28,054 km",Petrol,1st Owner,DL-9C,"₹9,693/month","₹5,33,399₹4,95,799",Nov 2019,NaN

Applying above changes to every different datasets containing diff locations, then combine all csv file in one.

## Merging Dataset: (Append)

In [11]:
new_delhi = pd.read_csv('new_delhi.csv')
mumbai = pd.read_csv('mumbai.csv')
kochi = pd.read_csv('kochi.csv')
jaipur = pd.read_csv('jaipur.csv')
kolkata = pd.read_csv('kolkata.csv')
lucknow = pd.read_csv('lucknow.csv')
chennai = pd.read_csv('chennai.csv')
hydrebad = pd.read_csv('hydrabad.csv')
bangalore = pd.read_csv('bangalore.csv')
indore = pd.read_csv('indore.csv')
pune = pd.read_csv('pune.csv')
ahmedabad = pd.read_csv('ahmedabad.csv')

In [18]:
new_delhi

,Name,Transmission,KM_Driven,Fuel_Type,Owner,Registration,EMI,Sales,Year,Types,City
0,2017 Hyundai Elite i20 ASTA 1.2 (O),MANUAL,"89,784 km",Petrol + CNG,1st Owner,HR-26,"?12,655/month","Fixed Price?6,47,299",Feb-17,CNG,New Delhi
1,2021 Maruti Alto LXI CNG,MANUAL,"30,144 km",Petrol + CNG,1st Owner,HR-26,"?9,396/month","?5,05,599?4,80,599",Feb-21,CNG,New Delhi
2,2018 Maruti Alto K10 LXI CNG (O),MANUAL,"83,128 km",Petrol + CNG,1st Owner,DL-2C,"?7,071/month","Fixed Price?3,61,699",Jun-18,CNG,New Delhi
3,2016 Maruti Alto K10 LXI CNG,MANUAL,"55,888 km",Petrol + CNG,2nd Owner,DL-8C,"?6,139/month","Fixed Price?3,13,999",May-16,CNG,New Delhi
4,2021 Maruti Alto LXI CNG,MANUAL,"17,920 km",Petrol + CNG,1st Owner,DL-3C,"?9,189/month","?5,07,699?4,69,999",Jul-21,CNG,New Delhi
...,...,...,...,...,...,...,...,...,...,...,...
233,2018 Hyundai Grand i10 SPORTZ 1.2 KAPPA VTVT,MANUAL,"6,875 km",Petrol,2nd Owner,UP-16,"?10,295/month","?5,46,999?5,26,599",Apr-18,NaN,New Delhi
234,2010 Hyundai i10 MAGNA 1.2,MANUAL,"19,940 km",Petrol,1st Owner,DL-10,"?3,353/month","?1,76,499?1,71,499",Sep-10,NaN,New Delhi
235,2011 Maruti Wagon R 1.0 VXI,MANUAL,"28,876 km",Petrol,1st Owner,DL-9C,"?5,523/month","Fixed Price?2,82,499",Jun-11,NaN,New Delhi
236,2020 KIA SELTOS HTK PLUS 1.5 PETROL,MANUAL,"6,436 km",Petrol,1st Owner,DL-11,"?21,868/month","?11,78,199?11,64,499",Oct-20,NaN,New Delhi
237,2019 Maruti Swift LXI,MANUAL,"28,054 km",Petrol,1st Owner,DL-9C,"?9,693/month","?5,33,399?4,95,799",Nov-19,NaN,New Delhi

In [12]:
c1 = new_delhi.append(mumbai, ignore_index = True)
c2 = c1.append(kochi, ignore_index = True)
c3 = c2.append(jaipur, ignore_index = True)
c4 = c3.append(kolkata, ignore_index = True)
c5 = c4.append(lucknow, ignore_index = True)
c6 = c5.append(chennai, ignore_index = True)
c7 = c6.append(hydrebad, ignore_index = True)
c8 = c7.append(bangalore, ignore_index = True)
c9 = c8.append(indore, ignore_index = True)
c10 = c9.append(pune, ignore_index = True)
cars24 = c10.append(ahmedabad, ignore_index = True)

C:\Users\ROHAN\AppData\Local\Temp\ipykernel_6072\295485310.py:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  c1 = new_delhi.append(mumbai, ignore_index = True)
C:\Users\ROHAN\AppData\Local\Temp\ipykernel_6072\295485310.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  c2 = c1.append(kochi, ignore_index = True)
C:\Users\ROHAN\AppData\Local\Temp\ipykernel_6072\295485310.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  c3 = c2.append(jaipur, ignore_index = True)
C:\Users\ROHAN\AppData\Local\Temp\ipykernel_6072\295485310.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  c4 = c3.append(kolkata, ignore_index = True)
C:\Users\ROHAN\AppData\Local\Temp\ipykernel_6072\295485310.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  c5 = c4.append(lucknow, ignore_index = True)
C:\Users\ROHAN\AppData\Local\Temp\ipykernel_6072\295485310.py:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  c6 = c5.append(chennai, ignore_index = True)
C:\Users\ROHAN\AppData\Local\Temp\ipykernel_6072\295485310.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  c7 = c6.append(hydrebad, ignore_index = True)
C:\Users\ROHAN\AppData\Local\Temp\ipykernel_6072\295485310.py:8: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  c8 = c7.append(bangalore, ignore_index = True)
C:\Users\ROHAN\AppData\Local\Temp\ipykernel_6072\295485310.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  c9 = c8.append(indore, ignore_index = True)
C:\Users\ROHAN\AppData\Local\Temp\ipykernel_6072\295485310.py:10: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  c10 = c9.append(pune, ignore_index = True)
C:\Users\ROHAN\AppData\Local\Temp\ipykernel_6072\295485310.py:11: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  cars24 = c10.append(ahmedabad, ignore_index = True)

In [13]:
cars24

,Name,Transmission,KM_Driven,Fuel_Type,Owner,Registration,EMI,Sales,Year,Types,City
0,2017 Hyundai Elite i20 ASTA 1.2 (O),MANUAL,"89,784 km",Petrol + CNG,1st Owner,HR-26,"?12,655/month","Fixed Price?6,47,299",Feb-17,CNG,New Delhi
1,2021 Maruti Alto LXI CNG,MANUAL,"30,144 km",Petrol + CNG,1st Owner,HR-26,"?9,396/month","?5,05,599?4,80,599",Feb-21,CNG,New Delhi
2,2018 Maruti Alto K10 LXI CNG (O),MANUAL,"83,128 km",Petrol + CNG,1st Owner,DL-2C,"?7,071/month","Fixed Price?3,61,699",Jun-18,CNG,New Delhi
3,2016 Maruti Alto K10 LXI CNG,MANUAL,"55,888 km",Petrol + CNG,2nd Owner,DL-8C,"?6,139/month","Fixed Price?3,13,999",May-16,CNG,New Delhi
4,2021 Maruti Alto LXI CNG,MANUAL,"17,920 km",Petrol + CNG,1st Owner,DL-3C,"?9,189/month","?5,07,699?4,69,999",Jul-21,CNG,New Delhi
...,...,...,...,...,...,...,...,...,...,...,...
2040,2018 Volkswagen Polo COMFORTLINE 1.0 PETROL,MANUAL,"27,071 km",Petrol,1st Owner,GJ-06,"?10,274/month","?5,45,499?5,25,499",Sep-18,NaN,Ahmedabad
2041,2021 Maruti Baleno ZETA 1.2 K12 CVT,AUTOMATIC,"3,735 km",Petrol,1st Owner,GJ-06,"?16,708/month","?9,44,899?8,89,699",Apr-21,NaN,Ahmedabad
2042,2021 Tata Safari XT 2.0 KRYOTEC,MANUAL,"11,835 km",Diesel,1st Owner,GJ-06,"?30,963/month","?18,57,199?16,48,799",Jun-21,NaN,Ahmedabad
2043,2021 Hyundai Creta S PETROL MT,MANUAL,"2,771 km",Petrol,1st Owner,GJ-27,"?23,141/month","?12,97,599?12,32,299",Nov-21,NaN,Ahmedabad
2044,2011 Maruti Swift VXI,MANUAL,"52,822 km",Petrol,1st Owner,GJ-01,"?6,397/month","Fixed Price?3,27,199",Jul-11,NaN,Ahmedabad

In [16]:
cars = cars24.sample(frac = 1).reset_index()
cars2 = cars.drop(['index'], axis = 1)
cars2

,Name,Transmission,KM_Driven,Fuel_Type,Owner,Registration,EMI,Sales,Year,Types,City
0,2020 Maruti New Wagon-R LXI CNG 1.0 L,MANUAL,"20,724 km",Petrol + CNG,1st Owner,DL-1C,"?11,626/month","Fixed Price?5,94,699",Sep-20,CNG,New Delhi
1,2017 Maruti Celerio ZXI OPT AMT,AUTOMATIC,"87,848 km",Petrol,1st Owner,TS-08-x-xxxx,"?8,893/month","?4,65,799?4,54,899",17-Jan,Maruti,Hyderabad
2,2010 Hyundai i10 ERA 1.1 IRDE,MANUAL,"60,476 km",Petrol,2nd Owner,KL-40,"?3,775/month","?2,29,099?1,93,099",Aug-10,NaN,Kochi
3,2013 Maruti Alto 800 LXI,MANUAL,"40,700 km",Petrol,1st Owner,TN-12-x-xxxx,"?5,019/month","Fixed Price?2,56,699",13-Jul,Cars from 2 lakh - 5 lakh,Chennai
4,2021 Mahindra XUV 3OO W8 (O) AT,NaN,"4,022 km",Petrol,1st Owner,MH-12,"?22,781/month","Fixed Price?12,13,099",Dec-21,Mahindra,Pune
...,...,...,...,...,...,...,...,...,...,...,...
2040,2021 Renault Duster RXZ CVT 1.3 TURBO,AUTOMATIC,"10,821 km",Petrol,1st Owner,DL-7C,"?27,010/month","?15,48,199?14,38,299",Oct-21,Renault,New Delhi
2041,2022 KIA SELTOS GTX PLUS 1.4G DCT DUAL TONE,NaN,"1,114 km",Petrol,1st Owner,KA-01-x-xxxx,"?39,614/month","?22,34,399?21,09,499",Feb-22,Cars above 10 lakh,Bangalore
2042,2020 Volkswagen Polo HIGH LINE PLUS 1.0,MANUAL,"17,595 km",Petrol,1st Owner,MH-14,"?15,337/month","Fixed Price?7,84,519",Feb-20,Petrol,Pune
2043,2020 Renault TRIBER 1.0 RXZ,MANUAL,"33,419 km",Petrol,1st Owner,TS-08-x-xxxx,"?12,563/month","?6,47,599?6,42,599",20-Jan,Renault,Hyderabad
2044,2018 Hyundai Tucson New 2WD MT PETROL,MANUAL,"86,670 km",Petrol,2nd Owner,UP-14,"?27,569/month","?15,83,199?14,68,099",Mar-18,MG,New Delhi

In [17]:
cars2.to_csv('scraped cars24 data (1).csv')